version: "3"
services:
  express-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
        - expressnet

  mysql:
      image: 'mysql/mysql-server:8.0'
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: "%"
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
      volumes:
          - 'express-mysql:/var/lib/mysql'
      networks:
          - expressnet
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s

networks:
    expressnet:
        driver: bridge
volumes:
    express-mysql:
        driver: local
