version: "3"
services:
  express-app:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev

  adminer:
      image: dockette/adminer:mysql
      restart: always
      ports:
          - 8080:80
      networks:
          - expressnet
